### ISSUE TITLE
Error when using CMS 9.0

### ISSUE THREAD

**Issue by prychel** [valdisiljuconoks/ImageResizer.Plugins.EPiServerBlobReader#4]
System.IO.FileNotFoundException: Could not load file or assembly 'EPiServer.BaseLibrary, Version=8.5.0.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7' or one of its dependencies. The system cannot find the file specified.
File name: 'EPiServer.BaseLibrary, Version=8.5.0.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7' ---> System.IO.FileNotFoundException: Could not load file or assembly 'EPiServer.BaseLibrary, Version=7.5.394.2, Culture=neutral, PublicKeyToken=8fe83dea738b45b7' or one of its dependencies. The system cannot find the file specified.
File name: 'EPiServer.BaseLibrary, Version=7.5.394.2, Culture=neutral, PublicKeyToken=8fe83dea738b45b7'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   at ImageResizer.Plugins.EPiServerBlobReader.EPiServerBlobFile.get_Content()
   at ImageResizer.Plugins.EPiServerBlobReader.EPiServerBlobFile.get_BlobExists()
   at ImageResizer.Configuration.PipelineConfig.GetFile(String virtualPath, NameValueCollection queryString)
   at ImageResizer.InterceptModule.CheckRequest_PostAuthorizeRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by valdisiljuconoks** [comment]
Resolved in latest version.
